### ISSUE TITLE
Weirdness upon switching from Core to Full

### ISSUE THREAD

**Issue by kelockhart** [adsabs/ADSCore#19]
1. Have an abstract page open with core=always. I also set my internet speed to slow 3G for testing.
2. In another tab, set core=never
3. In the original abstract page tab, click on a link - the page hydrates but takes me back to the home page and doesn't leave me on the hydrated abstract, or, ideally, drop me on the link I'd just clicked.

**Comment by marblestation** [comment]
This does not happen when we click on links that exist in core such as metrics, graphics or export. It only happens when we click on links such as citations, references, co-reads, similar, volume because those links just trigger a search (they are not a view in the abstract in core). Given that the cookie is set to never, the request is managed by BBB and not ADS Core (that's why a loading screen appears). But we still have problems with BBB and parameter queries (i.e., parameters sent after the `?`) and that's why it goes to the main search form instead of showing the query.

This is something to be fixed in BBB and the way it is deployed, so I'll close it here.
